language: python
python:
  - '2.7'

install:
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- -PX stable 2015.8.0
  - formula="users"
  - sudo mkdir /srv/salt; sudo cp -r $formula /srv/salt
  #- states=$(find /srv/salt -name '*.sls' | while read i; do tmp=$formula.${i##*/}; echo ${tmp%.*}; done | xargs | sed -e 's/ /,/g')
  - states=$(find /srv/salt -name '*.sls' | while read i; do tmp=$formula.${i##*/}; echo ${tmp%.*}; done | xargs)
  - echo $states

  # See what kind of travis box you're on to help with making your states compatible with travis
  - sudo salt-call grains.items --local

script:
  - for state in $(echo $states); do sudo salt-call state.show_sls --local --retcode-passthrough -l error test=True $state; done
