language: python
python:
  - '2.7'

before_install:
  - curl -L http://bootstrap.saltstack.org -o bootstrap_salt.sh
  - sudo sh bootstrap_salt.sh -P

install:
  # Copy these states
  - sudo mkdir -p /srv/salt/states
  - sudo cp -r . /srv/salt/states
  - cat .travis/minion
  - sudo cp .travis/minion /etc/salt/minion
  #- sudo service salt-minion restart

  # See what kind of travis box you're on to help with making your states compatible with travis
  - salt-call grains.items --local

script:
  - salt-call state.show_highstate --local retcode-passthrough
